name             'dns'
maintainer       'Fridolin Koch, Matthias Lang'
maintainer_email 'kochfr@in.tum.de, langm@in.tum.de'
license          'MIT'
description      'Installs/Configures dns'
long_description 'N/A'
version          '1.0.0'
