name             'ldap'
maintainer       'Fridolin Koch, Matthias Lang'
maintainer_email 'kochfr@in.tum.de, langm@in.tum.de'
license          'All rights reserved'
description      'Installs/Configures ldap'
long_description 'N/A'
version          '1.0.0'
